Repository YAPP-Github/onboard-server, pull requests merged in 2023-07, with the labels that each got.

#64 멤버 닉네임 검사 API 수정
  .github/workflows/ci.yml
  adapter-in/web/src/test/kotlin/com/yapp/bol/group/member/MemberControllerTest.kt
  core/src/main/kotlin/com/yapp/bol/group/member/MemberServiceImpl.kt
  core/src/test/kotlin/com/yapp/bol/group/member/MemberServiceImplTest.kt
  domain/src/main/kotlin/com/yapp/bol/group/member/Member.kt
  domain/src/test/kotlin/com/yapp/bol/member/MemberTest.kt
Labels: bug, enhancement

#60 BOL-109 feat: 가입한 그룹 목록 가져오기
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/dto/GroupReponse.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/user/UserController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/user/dto/JoinedGroupResponse.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/user/UserControllerTest.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupRepository.kt
  core/src/main/kotlin/com/yapp/bol/group/GroupServiceImpl.kt
  port-in/src/main/kotlin/com/yapp/bol/group/GroupService.kt
  port-out/src/main/kotlin/com/yapp/bol/group/GroupQueryRepository.kt
Labels: enhancement

#63 매치 관련 테이블을 설계
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/GameMemberEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchMemberEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/season/SeasonEntity.kt
  adapter-out/rdb/src/main/resources/sql.ddl/2023_05_14_CREATE_AUTH.sql
  adapter-out/rdb/src/main/resources/sql.ddl/2023_05_14_CREATE_USER.sql
  adapter-out/rdb/src/main/resources/sql.ddl/2023_06_03_CREATE_FILE.sql
  adapter-out/rdb/src/main/resources/sql.ddl/2023_06_06_CREATE_GROUP.sql
  adapter-out/rdb/src/main/resources/sql.ddl/2023_06_06_CREATE_MEMBER.sql
  adapter-out/rdb/src/main/resources/sql/ddl/2023_07_01_CREATE_GAME_MEMBER.sql
  adapter-out/rdb/src/main/resources/sql/ddl/2023_07_01_CREATE_MATCH.sql
  adapter-out/rdb/src/main/resources/sql/ddl/2023_07_01_CREATE_MATCH_MEMBER.sql
  adapter-out/rdb/src/main/resources/sql/ddl/2023_07_01_CREATE_SEASON.sql
Labels: enhancement

#62 BOL-116 fix: 그룹 소속으로 검색하기
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/GroupController.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/group/GroupControllerTest.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupRepository.kt
  core/src/main/kotlin/com/yapp/bol/group/GroupServiceImpl.kt
  port-in/src/main/kotlin/com/yapp/bol/group/GroupService.kt
  port-out/src/main/kotlin/com/yapp/bol/group/GroupQueryRepository.kt
Labels: enhancement

#65 BOL-94 fix: 맴버 조회 시 EmptyList 에러 해결
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepositoryImpl.kt
  adapter-out/rdb/src/test/kotlin/com/yapp/bol/group/member/MemberQueryRepositoryImplTest.kt
Labels: bug

#67 jpa OneToOne 연관관계 오류 해결
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/GameMemberEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchEntity.kt
Labels: bug

#66 BOL-146 feat: Group Default File Image 가져오기
  adapter-in/web/src/main/kotlin/com/yapp/bol/file/FileController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/file/dto/FileResponse.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/GroupController.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/group/GroupControllerTest.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/file/FileClient.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/file/FileEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/file/FileRepository.kt
  core/src/main/kotlin/com/yapp/bol/file/FileServiceImpl.kt
  domain/src/main/kotlin/com/yapp/bol/file/FilePurpose.kt
  port-in/src/main/kotlin/com/yapp/bol/file/FileService.kt
  port-out/src/main/kotlin/com/yapp/bol/file/FileQueryRepository.kt
Labels: enhancement

#68 BOL-153 feat: 로그인 시 남은 온보딩 보여주기
  adapter-in/web/src/main/kotlin/com/yapp/bol/auth/AuthController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/auth/dto/LoginResponse.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/auth/AuthControllerTest.kt
  core/src/main/kotlin/com/yapp/bol/onboarding/OnboardingServiceImpl.kt
  domain/src/main/kotlin/com/yapp/bol/onboarding/OnboardingType.kt
  port-in/src/main/kotlin/com/yapp/bol/onboarding/OnboardingService.kt
Labels: enhancement

#74 BOL-95 매치 기록 > port-out, adapter-out 추가
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/member/GameMemberCommandRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/member/GameMemberQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/member/GameMemberRepository.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchCommandRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchRepository.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/member/MatchMemberRepository.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/season/SeasonCommandRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/season/SeasonQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/season/SeasonRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/game/member/GameMemberCommandRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/game/member/GameMemberQueryRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/match/MatchCommandRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/season/SeasonCommandRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/season/SeasonQueryRepository.kt
Labels: enhancement

#80 BOL-95 매치 기록 > game 최소 인원 검증 로직 추가
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/GameClient.kt
  core/src/main/kotlin/com/yapp/bol/game/GameServiceImpl.kt
  core/src/main/kotlin/com/yapp/bol/game/member/GameMemberServiceImpl.kt
  domain/src/main/kotlin/com/yapp/bol/Exception.kt
  domain/src/main/kotlin/com/yapp/bol/game/member/GameMember.kt
  port-in/src/main/kotlin/com/yapp/bol/game/GameService.kt
  port-out/src/main/kotlin/com/yapp/bol/game/GameQueryRepository.kt
Labels: enhancement

#79 BOL-95 매치 기록 > 리팩터링
  adapter-in/web/src/main/kotlin/com/yapp/bol/match/dto/CreateMatchRequest.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/match/MatchControllerTest.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/GameClient.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/member/GameMemberEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchCommandRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/member/MatchMemberEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/member/MatchMemberRepository.kt
  adapter-out/rdb/src/main/resources/sql/ddl/2023_07_01_CREATE_MATCH.sql
  adapter-out/rdb/src/main/resources/sql/ddl/2023_07_01_CREATE_MATCH_MEMBER.sql
  core/src/main/kotlin/com/yapp/bol/game/GameServiceImpl.kt
  core/src/main/kotlin/com/yapp/bol/game/member/GameMemberServiceImpl.kt
  core/src/main/kotlin/com/yapp/bol/match/MatchServiceImpl.kt
  domain/src/main/kotlin/com/yapp/bol/Exception.kt
  domain/src/main/kotlin/com/yapp/bol/date/DateTimeUtils.kt
  domain/src/main/kotlin/com/yapp/bol/game/member/GameMember.kt
  domain/src/main/kotlin/com/yapp/bol/match/Match.kt
  domain/src/main/kotlin/com/yapp/bol/match/dto/MatchWithMatchMemberList.kt
  domain/src/main/kotlin/com/yapp/bol/match/member/MatchMember.kt
  domain/src/main/kotlin/com/yapp/bol/season/Season.kt
  domain/src/test/kotlin/com/yapp/bol/date/DateTimeUtilsTest.kt
  domain/src/test/kotlin/com/yapp/bol/game/member/GameMemberTest.kt
  port-in/src/main/kotlin/com/yapp/bol/game/GameService.kt
  port-in/src/main/kotlin/com/yapp/bol/game/member/GameMemberService.kt
  port-in/src/main/kotlin/com/yapp/bol/match/MatchService.kt
  port-in/src/main/kotlin/com/yapp/bol/match/dto/CreateMatchDto.kt
  port-out/src/main/kotlin/com/yapp/bol/game/GameQueryRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/match/MatchCommandRepository.kt
Labels: enhancement

#73 BOL-95 매치 기록 > 엔티티 수정
  adapter-in/web/src/main/kotlin/com/yapp/bol/match/MatchController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/match/dto/CreateMatchRequest.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/base/OpenApiTag.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/match/MatchControllerTest.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/GameClient.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/GameEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/GameMemberEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/member/GameMemberCommandRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/member/GameMemberEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/member/GameMemberQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/member/GameMemberRepository.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchCommandRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchMemberEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchRepository.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/member/MatchMemberEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/season/SeasonCommandRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/season/SeasonEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/season/SeasonQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/season/SeasonRepository.kt
  adapter-out/rdb/src/main/resources/sql/ddl/2023_07_01_CREATE_MATCH.sql
  adapter-out/rdb/src/main/resources/sql/ddl/2023_07_01_CREATE_MATCH_MEMBER.sql
  core/src/main/kotlin/com/yapp/bol/game/GameServiceImpl.kt
  core/src/main/kotlin/com/yapp/bol/game/member/GameMemberServiceImpl.kt
  core/src/main/kotlin/com/yapp/bol/match/MatchServiceImpl.kt
  core/src/main/kotlin/com/yapp/bol/season/SeasonServiceImpl.kt
  domain/src/main/kotlin/com/yapp/bol/Exception.kt
  domain/src/main/kotlin/com/yapp/bol/date/DateTimeUtils.kt
  domain/src/main/kotlin/com/yapp/bol/game/member/GameMember.kt
  domain/src/main/kotlin/com/yapp/bol/match/Match.kt
  domain/src/main/kotlin/com/yapp/bol/match/member/MatchMember.kt
  domain/src/main/kotlin/com/yapp/bol/season/Season.kt
  domain/src/test/kotlin/com/yapp/bol/date/DateTimeUtilsTest.kt
  domain/src/test/kotlin/com/yapp/bol/game/member/GameMemberTest.kt
  port-in/src/main/kotlin/com/yapp/bol/game/GameService.kt
  port-in/src/main/kotlin/com/yapp/bol/game/member/GameMemberService.kt
  port-in/src/main/kotlin/com/yapp/bol/match/MatchService.kt
  port-in/src/main/kotlin/com/yapp/bol/match/dto/CreateMatchDto.kt
  port-in/src/main/kotlin/com/yapp/bol/season/SeasonService.kt
  port-out/src/main/kotlin/com/yapp/bol/game/GameQueryRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/game/member/GameMemberCommandRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/game/member/GameMemberQueryRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/match/MatchCommandRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/season/SeasonCommandRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/season/SeasonQueryRepository.kt
Labels: enhancement, base

#83 BOL-328 Production 환경 세팅
  .github/workflows/ci-cd-production.yml
  .github/workflows/ci-cd-sandbox.yml
  .github/workflows/ci-cd.yml
  Dockerfile
  adapter-out/rdb/src/main/resources/application-rdb.yml
  adapter-out/rdb/src/main/resources/sql/ddl/2023_06_06_CREATE_GROUP.sql
  adapter-out/rdb/src/main/resources/sql/ddl/2023_06_06_CREATE_MEMBER.sql
  adapter-out/social/src/main/resources/application-social.yml
Labels: enhancement

#82 BoL-161 feat: 이용약관 API
  adapter-in/web/src/main/kotlin/com/yapp/bol/auth/AuthController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/auth/dto/LoginResponse.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/setting/SettingController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/terms/TermsController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/terms/dto/AgreeTermsRequest.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/terms/dto/TermsResponse.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/user/UserController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/user/dto/CheckOnboardResponse.kt
  adapter-in/web/src/main/resources/static/privacy.html
  adapter-in/web/src/main/resources/static/terms.html
  adapter-in/web/src/test/kotlin/com/yapp/bol/auth/AuthControllerTest.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/base/OpenApiTag.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/setting/SettingControllerTest.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/terms/TermsControllerTest.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/user/UserControllerTest.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/terms/TermsAgreeEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/terms/TermsAgreeRepository.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/terms/TermsCommandRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/terms/TermsQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/resources/sql/ddl/2023_07_10_CREATE_AGREED_TERMS.sql
  core/src/main/kotlin/com/yapp/bol/onboarding/OnboardingServiceImpl.kt
  core/src/main/kotlin/com/yapp/bol/terms/TermsServiceImpl.kt
  domain/src/main/kotlin/com/yapp/bol/Exception.kt
  domain/src/main/kotlin/com/yapp/bol/onboarding/OnboardingType.kt
  domain/src/main/kotlin/com/yapp/bol/terms/TermsAgreeInfo.kt
  domain/src/main/kotlin/com/yapp/bol/terms/TermsCode.kt
  port-in/src/main/kotlin/com/yapp/bol/terms/TermsService.kt
  port-out/src/main/kotlin/com/yapp/bol/terms/TermsCommandRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/terms/TermsQueryRepository.kt
Labels: enhancement

#69 BOL-108 리더보드 API
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/GroupController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/dto/LeaderBoardResponse.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/group/GroupControllerTest.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberRepository.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/match/MatchEntity.kt
  core/src/main/kotlin/com/yapp/bol/group/GroupServiceImpl.kt
  domain/src/main/kotlin/com/yapp/bol/group/LeaderBoardMember.kt
  port-in/src/main/kotlin/com/yapp/bol/group/GroupService.kt
  port-out/src/main/kotlin/com/yapp/bol/group/GroupQueryRepository.kt
Labels: enhancement

#84 BOL-241 멤버 닉네임 제약 추가
  core/src/main/kotlin/com/yapp/bol/group/member/MemberServiceImpl.kt
  core/src/main/kotlin/com/yapp/bol/user/UserServiceImpl.kt
  core/src/test/kotlin/com/yapp/bol/validate/NicknameValidatorTest.kt
  domain/src/main/kotlin/com/yapp/bol/group/member/Member.kt
  domain/src/main/kotlin/com/yapp/bol/validate/NicknameValidator.kt
Labels: enhancement
