Repository YAPP-Github/onboard-server, pull requests merged in 2023-06, with the labels that each got.

#34 BOL-35 그룹 생성- 도메인 객체 추가
  domain/src/main/kotlin/com/yapp/bol/group/Group.kt
  domain/src/main/kotlin/com/yapp/bol/group/member/Member.kt
  domain/src/main/kotlin/com/yapp/bol/group/member/MemberList.kt
  domain/src/main/kotlin/com/yapp/bol/group/member/MemberRole.kt
  domain/src/test/kotlin/com/yapp/bol/group/GroupTest.kt
  domain/src/test/kotlin/com/yapp/bol/member/MemberTest.kt
Labels: enhancement

#35 BOL-35 그룹 생성- port-out, adapter-out 추가
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupCommandRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupRepository.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberCommandRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberRepository.kt
  adapter-out/rdb/src/main/resources/application-rdb.yml
  adapter-out/rdb/src/main/resources/sql.ddl/2023_06_06_CREATE_GROUP.sql
  adapter-out/rdb/src/main/resources/sql.ddl/2023_06_06_CREATE_MEMBER.sql
  domain/src/main/kotlin/com/yapp/bol/group/member/MemberList.kt
  port-out/src/main/kotlin/com/yapp/bol/group/GroupCommandRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/group/GroupQueryRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/group/member/MemberCommandRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepository.kt
Labels: enhancement

#36 BOL-35 그룹 생성- 어댑터 추가
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/GroupController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/dto/CreateGroupRequest.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/dto/CreateGroupResponse.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/member/MemberController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/member/dto/ValidateMemberNameResponse.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/base/ControllerTest.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/base/OpenApiTag.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/group/GroupControllerTest.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/group/member/MemberControllerTest.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupCommandRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupRepository.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberRepository.kt
  adapter-out/rdb/src/main/resources/sql.ddl/2023_06_06_CREATE_GROUP.sql
  core/src/main/kotlin/com/yapp/bol/group/GroupServiceImpl.kt
  core/src/main/kotlin/com/yapp/bol/group/member/MemberServiceImpl.kt
  domain/src/main/kotlin/com/yapp/bol/Exception.kt
  domain/src/main/kotlin/com/yapp/bol/group/Group.kt
  domain/src/main/kotlin/com/yapp/bol/group/member/Member.kt
  domain/src/main/kotlin/com/yapp/bol/group/member/MemberList.kt
  domain/src/test/kotlin/com/yapp/bol/group/GroupTest.kt
  domain/src/test/kotlin/com/yapp/bol/member/MemberListTest.kt
  domain/src/test/kotlin/com/yapp/bol/member/MemberTest.kt
  port-in/src/main/kotlin/com/yapp/bol/group/GroupService.kt
  port-in/src/main/kotlin/com/yapp/bol/group/dto/CreateGroupDto.kt
  port-in/src/main/kotlin/com/yapp/bol/group/member/MemberService.kt
  port-out/src/main/kotlin/com/yapp/bol/group/GroupQueryRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepository.kt
Labels: enhancement

#39 BOL-35 그룹 생성
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/GroupController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/dto/CreateGroupRequest.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/dto/CreateGroupResponse.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/member/MemberController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/member/dto/ValidateMemberNameResponse.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/base/OpenApiTag.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/group/GroupControllerTest.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/group/member/MemberControllerTest.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/auth/AuthSocialRepository.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupCommandRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupRepository.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberCommandRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberRepository.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/user/UserRepository.kt
  adapter-out/rdb/src/main/resources/application-rdb.yml
  adapter-out/rdb/src/main/resources/sql.ddl/2023_06_06_CREATE_GROUP.sql
  adapter-out/rdb/src/main/resources/sql.ddl/2023_06_06_CREATE_MEMBER.sql
  core/src/main/kotlin/com/yapp/bol/group/GroupServiceImpl.kt
  core/src/main/kotlin/com/yapp/bol/group/member/MemberServiceImpl.kt
  domain/src/main/kotlin/com/yapp/bol/Exception.kt
  domain/src/main/kotlin/com/yapp/bol/group/Group.kt
  domain/src/main/kotlin/com/yapp/bol/group/GroupMemberList.kt
  domain/src/main/kotlin/com/yapp/bol/group/member/Member.kt
  domain/src/main/kotlin/com/yapp/bol/group/member/MemberList.kt
  domain/src/main/kotlin/com/yapp/bol/group/member/MemberRole.kt
  domain/src/test/kotlin/com/yapp/bol/group/GroupTest.kt
  domain/src/test/kotlin/com/yapp/bol/member/MemberListTest.kt
  domain/src/test/kotlin/com/yapp/bol/member/MemberTest.kt
  port-in/src/main/kotlin/com/yapp/bol/group/GroupService.kt
  port-in/src/main/kotlin/com/yapp/bol/group/dto/CreateGroupDto.kt
  port-in/src/main/kotlin/com/yapp/bol/group/member/MemberService.kt
  port-in/src/main/kotlin/com/yapp/bol/group/member/dto/CreateMemberDto.kt
  port-out/src/main/kotlin/com/yapp/bol/group/GroupCommandRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/group/GroupQueryRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/group/member/MemberCommandRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepository.kt
Labels: enhancement, base

#45 BOL-60 그룹 검색 API
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/GroupController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/dto/CreateGroupRequest.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/dto/CreateGroupResponse.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/group/GroupControllerTest.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupRepository.kt
  adapter-out/rdb/src/main/resources/sql.ddl/2023_06_06_CREATE_GROUP.sql
  core/src/main/kotlin/com/yapp/bol/group/GroupServiceImpl.kt
  core/src/main/kotlin/com/yapp/bol/group/member/MemberServiceImpl.kt
  domain/src/main/kotlin/com/yapp/bol/group/Group.kt
  domain/src/main/kotlin/com/yapp/bol/group/dto/GroupMemberList.kt
  domain/src/main/kotlin/com/yapp/bol/group/dto/GroupWithMemberCount.kt
  domain/src/main/kotlin/com/yapp/bol/group/member/MemberList.kt
  domain/src/main/kotlin/com/yapp/bol/pageable/PaginationCursor.kt
  port-in/src/main/kotlin/com/yapp/bol/group/GroupService.kt
  port-in/src/main/kotlin/com/yapp/bol/group/dto/CreateGroupDto.kt
  port-in/src/main/kotlin/com/yapp/bol/group/member/MemberService.kt
  port-out/src/main/kotlin/com/yapp/bol/group/GroupQueryRepository.kt
Labels: enhancement

#50 BOL-60 그룹 검색 API, 그룹 전체 검색 가능하도록 수정
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/GroupController.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/group/GroupControllerTest.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupQueryRepositoryImpl.kt
  core/src/main/kotlin/com/yapp/bol/group/GroupServiceImpl.kt
  domain/src/main/kotlin/com/yapp/bol/pageable/PaginationCursor.kt
  domain/src/main/kotlin/com/yapp/bol/pageable/PaginationCursor.kt~BOL-60 refactor: ApplicationSlice -> PaginationCursor 이름 변경
  domain/src/main/kotlin/com/yapp/bol/pageable/PaginationCursor.kt~dev
  port-in/src/main/kotlin/com/yapp/bol/group/GroupService.kt
  port-out/src/main/kotlin/com/yapp/bol/group/GroupQueryRepository.kt
Labels: enhancement

#52 BOL-92 게임 목록 내려주기
  adapter-in/web/src/main/kotlin/com/yapp/bol/file/FileController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/game/GameController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/game/dto/GameListResponse.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/game/dto/GameResponse.kt
  adapter-in/web/src/main/resources/application.yml
  adapter-in/web/src/test/kotlin/com/yapp/bol/base/OpenApiTag.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/file/FileControllerTest.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/game/GameControllerTest.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/file/FileClient.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/file/FileNameConverter.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/GameClient.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/GameEntity.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/game/GameRepository.kt
  adapter-out/rdb/src/main/resources/application-rdb.yml
  adapter-out/rdb/src/main/resources/sql/ddl/2023_05_14_CREATE_AUTH.sql
  adapter-out/rdb/src/main/resources/sql/ddl/2023_05_14_CREATE_USER.sql
  adapter-out/rdb/src/main/resources/sql/ddl/2023_06_03_CREATE_FILE.sql
  adapter-out/rdb/src/main/resources/sql/ddl/2023_06_13_CREATE_GAME.sql
  adapter-out/rdb/src/main/resources/sql/dml/2023_06_13_INSERT_GAMES.sql
  core/src/main/kotlin/com/yapp/bol/game/GameServiceImpl.kt
  port-in/src/main/kotlin/com/yapp/bol/game/GameService.kt
  port-out/src/main/kotlin/com/yapp/bol/game/GameQueryRepository.kt
Labels: base

#53 BOL-112 내 정보 가져오기
  adapter-in/web/src/main/kotlin/com/yapp/bol/user/UserController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/user/dto/MyInfoResponse.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/base/OpenApiTag.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/user/UserControllerTest.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/user/UserClient.kt
  core/src/main/kotlin/com/yapp/bol/user/UserServiceImpl.kt
  domain/src/main/kotlin/com/yapp/bol/Exception.kt
  domain/src/main/kotlin/com/yapp/bol/user/User.kt
  port-in/src/main/kotlin/com/yapp/bol/user/UserService.kt
  port-out/src/main/kotlin/com/yapp/bol/user/UserQueryRepository.kt
Labels: enhancement

#55 BOL-94-2 맴버 목록 가져오기
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/member/MemberController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/member/dto/MemberResponse.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/group/member/MemberControllerTest.kt
  adapter-out/rdb/build.gradle.kts
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/config/QueryDslConfiguration.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/CustomMemberRepository.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/CustomMemberRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberRepository.kt
  adapter-out/rdb/src/test/kotlin/com/yapp/bol/group/member/MemberQueryRepositoryImplTest.kt
  core/src/main/kotlin/com/yapp/bol/group/member/MemberServiceImpl.kt
  core/src/test/kotlin/com/yapp/bol/group/member/MemberServiceImplTest.kt
  domain/src/main/kotlin/com/yapp/bol/pagination/SimpleCursorResponse.kt
  gradle.properties
  port-in/src/main/kotlin/com/yapp/bol/group/dto/GetMembersByCursorDto.kt
  port-in/src/main/kotlin/com/yapp/bol/group/member/MemberService.kt
  port-out/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepository.kt
  settings.gradle.kts
Labels: enhancement

#59 커서 기반 페이지네이션 리팩터링
  README.md
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/GroupController.kt
  adapter-in/web/src/main/kotlin/com/yapp/bol/group/member/MemberController.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/group/GroupControllerTest.kt
  adapter-in/web/src/test/kotlin/com/yapp/bol/group/member/MemberControllerTest.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/GroupQueryRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/CustomMemberRepository.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/CustomMemberRepositoryImpl.kt
  adapter-out/rdb/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepositoryImpl.kt
  adapter-out/rdb/src/test/kotlin/com/yapp/bol/group/member/MemberQueryRepositoryImplTest.kt
  core/src/main/kotlin/com/yapp/bol/group/GroupServiceImpl.kt
  core/src/main/kotlin/com/yapp/bol/group/member/MemberServiceImpl.kt
  core/src/test/kotlin/com/yapp/bol/group/member/MemberServiceImplTest.kt
  domain/src/main/kotlin/com/yapp/bol/group/member/dto/PaginationCursorMemberRequest.kt
  domain/src/main/kotlin/com/yapp/bol/pageable/PaginationCursor.kt
  domain/src/main/kotlin/com/yapp/bol/pagination/CursorRequest.kt
  domain/src/main/kotlin/com/yapp/bol/pagination/CursorResponse.kt
  domain/src/main/kotlin/com/yapp/bol/pagination/SimpleCursorRequest.kt
  domain/src/main/kotlin/com/yapp/bol/pagination/SimpleCursorResponse.kt
  domain/src/main/kotlin/com/yapp/bol/pagination/cursor/PaginationCursorRequest.kt
  domain/src/main/kotlin/com/yapp/bol/pagination/cursor/PaginationCursorResponse.kt
  domain/src/main/kotlin/com/yapp/bol/pagination/cursor/SimplePaginationCursorRequest.kt
  domain/src/main/kotlin/com/yapp/bol/pagination/cursor/SimplePaginationCursorResponse.kt
  domain/src/main/kotlin/com/yapp/bol/pagination/offset/PaginationOffsetResponse.kt
  port-in/src/main/kotlin/com/yapp/bol/group/GroupService.kt
  port-in/src/main/kotlin/com/yapp/bol/group/dto/GetMembersByCursorDto.kt
  port-in/src/main/kotlin/com/yapp/bol/group/member/MemberService.kt
  port-out/src/main/kotlin/com/yapp/bol/group/GroupQueryRepository.kt
  port-out/src/main/kotlin/com/yapp/bol/group/member/MemberQueryRepository.kt
Labels: base

#61 그룹 생성 스웨거 오류 해결
  adapter-in/web/src/test/kotlin/com/yapp/bol/group/GroupControllerTest.kt
Labels: bug
